app:
  port: 0 # 0 means random port
  logging:
    development: true
    jsonOutputMode: false
    logLevel: DEBUG

  datasource:
    driver: mysql
    host: localhost
    port: 3306
    database: sample_test
    username: root
    password: secret
    params: parseTime=true
    migrationSource: file://../../migration/migrations

  kafka:
    bootstrapServers: localhost:9092
    clientId: golib-sample-test
    admin:
      topics:
        - name: c1.order.order-created.test
          partitions: 1
          replicaFactor: 1
          retention: 72h
    producer:
      flushMessages: 1
      flushFrequency: 1s
      eventMappings:
        OrderCreatedEvent:
          topicName: c1.order.order-created.test
          transactional: false
    consumer:
      initialOffset: -2
      handlerMappings:
        OrderCreatedEventDummyHandler:
          topic: c1.order.order-created.test
          groupId: c1.order.order-created.OrderCreatedEventDummyHandler.local
          enable: true

  httpclient:
    timeout: 60s
    proxy:
      url: http://localhost:8088
      applied_uris:
        - https://order.sample.api/
        - https://foo.local/

  security:
    http:
      client:
        basicAuth:
          - { urlMatch: "https://order.sample.api/.*", username: guest, password: secret }

  services:
    order:
      baseUrl: https://order.sample.api
      getOrderByIdPath: /orders/%d
