include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: "/common/libs-next-gen.yml"
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: "before-script-templates.yml"

default:
  tags: [ vincart-nonprod ]
  image: asia.gcr.io/vinid-devops/k8s-deployer:latest

cache:
  key: "$CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME"
  paths:
    - /go/pkg/mod

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - verify
  - docker_build
  - deploy
  - tag
  - request deploy to production

.test:
  stage: verify
  allow_failure: false
  image: golang:1.17-alpine
  tags:
    - vincart-nonprod
  except:
    refs:
      - tags
  before_script:
    - apk update && apk add git build-base
    - export GOPRIVATE=gitlab.id.vin
    - git config --global url."https://$GITLAB_USER:$GITLAB_ACCESS_TOKEN@gitlab.id.vin/".insteadOf "https://gitlab.id.vin/"

automation test:
  extends: .test
  services:
    - name: asia.gcr.io/vinid-devops/mysql:5.7
      alias: mysql
    - name: wurstmeister/kafka
      alias: kafka
    - name: wurstmeister/zookeeper
      alias: zookeeper
    - name: asia.gcr.io/vinid-devops/redis:5.0.6
      alias: redis
  variables:
    KAFKA_ADVERTISED_HOST_NAME: "kafka"
    KAFKA_LISTENERS: "PLAINTEXT://:9092"
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    MYSQL_DATABASE: sample_test
    MYSQL_ROOT_PASSWORD: secret
    APP_DATASOURCE_HOST: mysql
    APP_REDIS_HOST: redis
    APP_KAFKA_BOOTSTRAPSERVERS: kafka:9092
  script:
    - cd $CI_PROJECT_DIR/src/core && go test ./...
    - cd $CI_PROJECT_DIR/src/adapter && go test ./...
    - cd $CI_PROJECT_DIR/src/internal && go test ./...
