version: '2.2'

services:
  mysql:
    container_name: golib-sample-mysql
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./docker/mysql/init-database-test.sql:/docker-entrypoint-initdb.d/init-database-test.sql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
  redis:
    container_name: golib-sample-redis
    image: redis:5.0.6
    ports:
      - "6379:6379"
  zookeeper:
    container_name: golib-sample-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: golib-sample-kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
