app:
  port: 8081
  logging.development: true
  swagger.enabled: true

  redis:
    host: localhost
    port: 6379

  datasource:
    driver: mysql
    host: localhost
    port: 3306
    database: sample
    username: root
    password: secret
    params: parseTime=true

  kafka:
    bootstrapServers: localhost:9092
    clientId: golib-sample
    admin:
      topics:
        - name: c1.order.order-created
          partitions: 1
          replicaFactor: 1
          retention: 72h
    producer:
      eventMappings:
        OrderCreatedEvent:
          topicName: c1.order.order-created
          transactional: false
