app:
  port: 8081
  logging.development: true

  kafka:
    bootstrapServers: localhost:9092
    clientId: golib-sample
    consumer:
      handlerMappings:
        SendOrderToDeliveryProviderHandler:
          topic: c1.order.order-created
          groupId: c1.order.order-created.SendOrderToDeliveryProviderHandler.local
          enable: true

  security:
    http:
      client:
        basicAuth:
          - { urlMatch: "https://order.sample.api/.*", username: guest, password: "${ORDER_DELIVERY_SERVICE_PASSWORD}" }

  services:
    delivery:
      baseUrl: https://order.sample.api/v1
      createOrderPath: /orders
