app:
  port: -1 # -1 means random port
  logging.development: true

  kafka:
    bootstrapServers: localhost:9092
    clientId: golib-sample-test
    admin:
      topics:
        - name: c1.order.order-created.test
          partitions: 1
          replicaFactor: 1
          retention: 72h
    producer:
      eventMappings:
        OrderCreatedEvent:
          topicName: c1.order.order-created.test
          transactional: false
    consumer:
      commitMode: AUTO_COMMIT_IMMEDIATELY
      handlerMappings:
        OrderCreatedEventDummyHandler:
          topic: c1.order.order-created.test
          groupId: c1.order.order-created.OrderCreatedEventDummyHandler.test
          enable: true
        SendOrderToDeliveryProviderHandler:
          topic: c1.order.order-created.test
          groupId: c1.order.order-created.SendOrderToDeliveryProviderHandler.test
          enable: true

  security:
    http:
      client:
        basicAuth:
          - { urlMatch: "https://order.sample.api/.*", username: guest, password: secret }

  services:
    delivery:
      baseUrl: https://order.sample.api/v1
      createOrderPath: /orders
