definitions:
  entity.PaymentMethod:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  response.Meta:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.Response:
    properties:
      data:
        type: object
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
info:
  contact: {}
  title: Configuration Service Internal API
  version: 1.0.0
paths:
  /v1/merchants/{code}/services/{service_code}/payment-methods:
    get:
      consumes:
      - application/json
      parameters:
      - description: merchant code
        in: path
        name: code
        required: true
        type: string
      - description: service code
        in: path
        name: service_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.PaymentMethod'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BasicAuth: []
      summary: Get Payment Methods
      tags:
      - MerchantConfigController
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
