app:
  port: 8080
  logging.development: true
  swagger.enabled: true

  redis:
    host: localhost
    port: 6379

  datasource:
    driver: mysql
    host: localhost
    port: 3306
    database: sample
    username: root
    password: secret
    params: parseTime=true

  kafka:
    bootstrapServers: localhost:9092
    clientId: golib-sample
    admin:
      topics:
        - name: c1.http.request-completed
          partitions: 1
          replicaFactor: 1
          retention: 72h
        - name: c1.order.order-created
          partitions: 1
          replicaFactor: 1
          retention: 72h
    producer:
      eventMappings:
        RequestCompletedEvent:
          topicName: c1.http.request-completed
          transactional: false
        OrderCreatedEvent:
          topicName: c1.order.order-created
          transactional: false

  security:
    http:
      jwt.publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAibfYgV1ACadMfuvl5VsR
        V0H/llbi+zB0f6kTSQ0VwzNR9eYbn8vFUaf3RXA8rxdICtKq8dB23F+2+GICIkjt
        cHwC1DtcvfxbpOPLYCrZKLntlzRR2UJOzKTq0JP+ea/zydEYIHR9uVIZarw1vz9R
        LqtiIvZZFUQtDmnc9f7R9kp6XmZgoqg8/hMZ7SF9GvDmdDZSjLCoKrKXHO3a2djn
        L7FwbiOr8Qx2Zlbm+rzZ3ovIXvskIJqg/S7PFg55Xt8oxL4NxaqzxiEVnZMqEGba
        pLzetqErEg73L93r7DdnSc4O55qTrRxXMWE+pRx1jWAFdcQL0kZ1TJf/OnNXKKHw
        aQIDAQAB
        -----END PUBLIC KEY-----
