definitions:
  resource.CreateOrderRequest:
    properties:
      total_amount:
        type: integer
    type: object
  resource.Order:
    properties:
      created_at:
        type: integer
      id:
        type: integer
      total_amount:
        type: integer
      user_id:
        type: string
    type: object
  response.Meta:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.Response:
    properties:
      data: { }
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
info:
  contact: { }
  title: Sample Public API
  version: 1.0.0
paths:
  /v1/orders:
    post:
      consumes:
        - application/json
      parameters:
        - description: Request body
          in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/resource.CreateOrderRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/response.Response'
              - properties:
                  data:
                    $ref: '#/definitions/resource.Order'
                type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
        - BearerAuth: [ ]
      summary: Create order
      tags:
        - OrderController
  /v1/orders/{id}:
    get:
      consumes:
        - application/json
      parameters:
        - description: order id
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/response.Response'
              - properties:
                  data:
                    $ref: '#/definitions/resource.Order'
                type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
        - BearerAuth: [ ]
      summary: Get order by ID
      tags:
        - OrderController
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
